schema_data_types:
  Div: "string"
  Date: "string"
  Time: "string"
  HomeTeam: "string"
  AwayTeam: "string"
  FTHG: "Int64"
  FTAG: "Int64"
  FTR: "string"
  HTHG: "Int64"
  HTAG: "Int64"
  HTR: "string"
  Referee: "string"
  HS: "Int64"
  AS: "Int64"
  HST: "Int64"
  AST: "Int64"
  HF: "Int64"
  AF: "Int64"
  HC: "Int64"
  AC: "Int64"
  HY: "Int64"
  AY: "Int64"
  HR: "Int64"
  AR: "Int64"
  B365H: "float64"
  B365D: "float64"
  B365A: "float64"
  BWH: "float64"
  BWD: "float64"
  BWA: "float64"
  IWH: "float64"
  IWD: "float64"
  IWA: "float64"
  PSH: "float64"
  PSD: "float64"
  PSA: "float64"
  WHH: "float64"
  WHD: "float64"
  WHA: "float64"
  VCH: "float64"
  VCD: "float64"
  VCA: "float64"
  MaxH: "float64"
  MaxD: "float64"
  MaxA: "float64"
  AvgH: "float64"
  AvgD: "float64"
  AvgA: "float64"
  B365>2.5: "float64"
  B365<2.5: "float64"
  P>2.5: "float64"
  P<2.5: "float64"
  Max>2.5: "float64"
  Max<2.5: "float64"
  Avg>2.5: "float64"
  Avg<2.5: "float64"
  AHh: "float64"
  B365AHH: "float64"
  B365AHA: "float64"
  PAHH: "float64"
  PAHA: "float64"
  MaxAHH: "float64"
  MaxAHA: "float64"
  AvgAHH: "float64"
  AvgAHA: "float64"
  B365CH: "float64"
  B365CD: "float64"
  B365CA: "float64"
  BWCH: "float64"
  BWCD: "float64"
  BWCA: "float64"
  IWCH: "float64"
  IWCD: "float64"
  IWCA: "float64"
  PSCH: "float64"
  PSCD: "float64"
  PSCA: "float64"
  WHCH: "float64"
  WHCD: "float64"
  WHCA: "float64"
  VCCH: "float64"
  VCCD: "float64"
  VCCA: "float64"
  MaxCH: "float64"
  MaxCD: "float64"
  MaxCA: "float64"
  AvgCH: "float64"
  AvgCD: "float64"
  AvgCA: "float64"
  B365C>2.5: "float64"
  B365C<2.5: "float64"
  PC>2.5: "float64"
  PC<2.5: "float64"
  MaxC>2.5: "float64"
  MaxC<2.5: "float64"
  AvgC>2.5: "float64"
  AvgC<2.5: "float64"
  AHCh: "float64"
  B365CAHH: "float64"
  B365CAHA: "float64"
  PCAHH: "float64"
  PCAHA: "float64"
  MaxCAHH: "float64"
  MaxCAHA: "float64"
  AvgCAHH: "float64"
  AvgCAHA: "float64"
  # Columns added by Preprocessor and used by features
  match_date: "datetime64[ns]"
  home_team_idx: "Int64"
  away_team_idx: "Int64"
